//go:build with_lxd

package lxd

import (
	"bytes"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"net"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	E "github.com/sagernet/sing/common/exceptions"
)

// DaemonConfig is the daemon's own base configuration, living in ITS state
// directory (<state-dir>/daemon.json, 0600) — not in the service unit and not
// in any client's directory. The service plist then degenerates to
// `sing-box lxd --state-dir <dir>`: changing the listen address or the secret
// is a file edit + restart, not a service reinstall, and the Bearer secret is
// owned by the daemon (root) instead of leaking into a launcher-owned file
// (SPEC 057: the secret is the daemon's credential, so the daemon keeps it).
//
// This file is the ONLY source of the daemon's connection settings — the lxd
// command has no connection flags at all, so "which side wins" cannot be
// asked. Absent file = fixed dev defaults.
type DaemonConfig struct {
	// Listen is the control channel address: one "host:port" string, or an
	// object with several addresses sharing one port (see ListenConfig).
	Listen ListenConfig `json:"listen,omitempty"`
	// TLS enables the mTLS control plane with client enrollment.
	TLS bool `json:"tls,omitempty"`
	// Secret is the Bearer secret for the operator routes (and the only gate
	// when TLS is off). Generated by the daemon on install when absent.
	Secret string `json:"secret,omitempty"`

	// LogFile overrides where the daemon-owned rotated log lives. Absent = the
	// derived default (<parent of state-dir>/lxd.log, see DefaultLogPath). A
	// relative path is resolved against the daemon's cwd at startup — a service
	// unit runs with cwd "/", so an installed daemon should use an absolute
	// path. The point of the override is media placement: on OpenWrt the
	// installer sets /tmp/lxd.log so the log lives on tmpfs instead of wearing
	// the overlay flash.
	LogFile string `json:"log_file,omitempty"`
	// Log rotation limits for the daemon-owned log file (see logrotate.go).
	// Zero or absent = defaults (1 MB, 1 backup, 24 h — about a day of
	// history); there is deliberately no "unlimited" setting.
	LogMaxSizeMB   int `json:"log_max_size_mb,omitempty"`
	LogMaxBackups  int `json:"log_max_backups,omitempty"`
	LogMaxAgeHours int `json:"log_max_age_hours,omitempty"`

	// DHCPLeaseFiles overrides where the client directory (SPEC 066) looks for
	// DHCP leases. Absent = the distro conventions in defaultLeaseFiles(),
	// OpenWrt's /tmp/dhcp.leases first. Only needed for a server that keeps its
	// leases somewhere unusual.
	DHCPLeaseFiles []string `json:"dhcp_lease_files,omitempty"`
}

// ListenConfig is the control channel's bind spec. Two JSON forms, one
// meaning — a list of "host:port" addresses to serve the same two planes on:
//
//	"listen": "127.0.0.1:19091"
//	"listen": {"address": ["192.168.10.1", "127.0.0.1"], "port": 19091}
//
// The string form is the original one and stays exact — daemon.json files
// written before this existed keep working, and a single address needs no
// object. The object form exists because one address is genuinely not enough:
// a daemon reachable from a LAN interface AND from loopback cannot be
// expressed as one bind, and 0.0.0.0 is not the answer — it also exposes every
// other interface the host happens to have.
//
// Addresses are bind targets, not filters: each becomes its own listener on a
// shared http.Server. There is deliberately no netmask syntax ("192.168.10.1/32")
// — a mask cannot be honoured (the kernel binds one address, never a range),
// so accepting one would only let the file claim something the daemon does not
// do. Restricting WHO may connect is the firewall's job, not this field's.
type ListenConfig struct {
	// Address holds one or more bind hosts. In the string form it is the whole
	// "host:port" (Port stays zero); in the object form the hosts are bare and
	// share Port.
	Address []string `json:"address,omitempty"`
	// Port is the shared port of the object form, unset in the string form.
	Port uint16 `json:"port,omitempty"`
}

// listenConfigObject mirrors ListenConfig for JSON without inheriting its
// custom marshalling — decoding the object form into ListenConfig itself would
// recurse through UnmarshalJSON forever.
type listenConfigObject struct {
	Address []string `json:"address,omitempty"`
	Port    uint16   `json:"port,omitempty"`
}

// UnmarshalJSON accepts the string and the object form. Both are validated
// here rather than at bind time: a daemon.json that cannot produce a single
// address must fail while the operator is looking at the error, not later as a
// daemon listening nowhere.
func (l *ListenConfig) UnmarshalJSON(content []byte) error {
	var single string
	if err := json.Unmarshal(content, &single); err == nil {
		if single == "" {
			return E.New("listen: empty address")
		}
		*l = ListenConfig{Address: []string{single}}
		return l.validate()
	}
	var object listenConfigObject
	decoder := json.NewDecoder(bytes.NewReader(content))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&object); err != nil {
		return E.Cause(err, "listen: expected \"host:port\" or {\"address\": [...], \"port\": N}")
	}
	*l = ListenConfig{Address: object.Address, Port: object.Port}
	return l.validate()
}

// MarshalJSON writes back the form the value came in as: a lone "host:port"
// stays a string, so install/rewrite paths do not silently convert existing
// single-address files into the object form.
func (l ListenConfig) MarshalJSON() ([]byte, error) {
	if l.Port == 0 && len(l.Address) == 1 {
		return json.Marshal(l.Address[0])
	}
	return json.Marshal(listenConfigObject{Address: l.Address, Port: l.Port})
}

func (l *ListenConfig) validate() error {
	if len(l.Address) == 0 {
		return E.New("listen: no address")
	}
	seen := make(map[string]bool, len(l.Address))
	for _, address := range l.Address {
		if address == "" {
			return E.New("listen: empty address")
		}
		// A mask is the one wrong-shaped input worth naming explicitly: it
		// looks plausible and would otherwise fail as an opaque bind error.
		if strings.Contains(address, "/") {
			return E.New("listen: ", address, ": netmasks are not supported — give the bare address to bind")
		}
		resolved, err := l.addressOf(address)
		if err != nil {
			return err
		}
		if seen[resolved] {
			return E.New("listen: duplicate address ", resolved)
		}
		seen[resolved] = true
	}
	return nil
}

// addressOf renders one entry as the "host:port" net.Listen takes: with Port
// set the entry is a bare host, without it the entry already carries its port.
func (l ListenConfig) addressOf(address string) (string, error) {
	if l.Port != 0 {
		if _, _, err := net.SplitHostPort(address); err == nil {
			return "", E.New("listen: ", address, " already carries a port, but \"port\" is set too")
		}
		return net.JoinHostPort(address, strconv.Itoa(int(l.Port))), nil
	}
	host, port, err := net.SplitHostPort(address)
	if err != nil {
		return "", E.Cause(err, "listen: ", address, ": expected \"host:port\" (or set \"port\" and list bare addresses)")
	}
	if port == "" {
		return "", E.New("listen: ", address, ": empty port")
	}
	return net.JoinHostPort(host, port), nil
}

// Addresses returns every "host:port" to bind, in file order.
func (l ListenConfig) Addresses() []string {
	addresses := make([]string, 0, len(l.Address))
	for _, address := range l.Address {
		resolved, err := l.addressOf(address)
		if err != nil {
			// Unreachable for a validated value; keeping the raw entry makes
			// the eventual bind error name what the file actually said.
			resolved = address
		}
		addresses = append(addresses, resolved)
	}
	return addresses
}

// Advertise returns the address clients are pointed at — enrollment invites,
// the local client, install's summary. It is the FIRST configured address:
// with several binds the file's order is the operator's own preference, and
// the daemon has no better ground to pick from (a loopback bind is not
// reachable for a remote launcher, a LAN bind is not for a local tool).
func (l ListenConfig) Advertise() string {
	addresses := l.Addresses()
	if len(addresses) == 0 {
		return ""
	}
	return addresses[0]
}

// IsZero reports the absent field, so callers can fall back to their defaults.
func (l ListenConfig) IsZero() bool {
	return len(l.Address) == 0
}

// ListenAddress builds the single-address form used by dev defaults, the
// install-time port scan, and tests.
func ListenAddress(address string) ListenConfig {
	return ListenConfig{Address: []string{address}}
}

const daemonConfigFile = "daemon.json"

func daemonConfigPath(stateDir string) string {
	return filepath.Join(stateDir, daemonConfigFile)
}

// LoadDaemonConfig reads <stateDir>/daemon.json. Absence is not an error:
// (zero, false, nil) — callers fall back to flag defaults. A present but
// unreadable/corrupt file IS an error: silently ignoring it would boot the
// daemon with a different address/secret than the operator configured.
func LoadDaemonConfig(stateDir string) (DaemonConfig, bool, error) {
	content, found, err := readOptional(daemonConfigPath(stateDir))
	if err != nil || !found {
		return DaemonConfig{}, false, err
	}
	var config DaemonConfig
	if err = json.Unmarshal([]byte(content), &config); err != nil {
		return DaemonConfig{}, false, E.Cause(err, "parse ", daemonConfigFile)
	}
	return config, true, nil
}

// SaveDaemonConfig persists daemon.json atomically with 0600 (the file holds
// the Bearer secret), creating the state directory (0700) when needed.
func SaveDaemonConfig(stateDir string, config DaemonConfig) error {
	stateStore, err := newStore(stateDir)
	if err != nil {
		return err
	}
	encoded, err := json.MarshalIndent(config, "", "  ")
	if err != nil {
		return err
	}
	return stateStore.writeAtomic(daemonConfigPath(stateDir), append(encoded, '\n'))
}

// GenerateSecret returns a fresh Bearer secret: 32 random bytes, lowercase
// hex. Brute force over the network is hopeless; the value lives only in
// daemon.json (0600, daemon-owned).
func GenerateSecret() (string, error) {
	var buf [32]byte
	if _, err := rand.Read(buf[:]); err != nil {
		return "", E.Cause(err, "generate secret")
	}
	return hex.EncodeToString(buf[:]), nil
}

// FindServiceStateDir returns the state directory of an installed service:
// the first scope (system, then user) whose daemon.json exists. found=false
// when neither scope has one. Used by the `client` subcommands and uninstall
// paths so `sudo sing-box lxd client add` works with no flags on a host with
// an installed service.
func FindServiceStateDir() (string, bool) {
	for _, user := range []bool{false, true} {
		dir := DefaultServiceStateDir(user)
		if _, err := os.Stat(daemonConfigPath(dir)); err == nil {
			return dir, true
		}
	}
	return "", false
}
