package libbox

// # Why this test exists
//
// Every exported method of a gomobile-bound type (and every exported package-level
// function) is reachable from Java/Kotlin and from Objective-C/Swift through a
// generated cgo boundary. cmd/cgo writes that boundary as `//export proxy<pkg>_<Type>_<Method>`
// and, because a Go function can only return one value plus an error, it packs the
// results into a C struct that the Go side fills in through a pointer handed over by
// the caller:
//
//	//export proxylibbox_Thing_GetName
//	func proxylibbox_Thing_GetName(refnum C.int32_t) (C.nstring, C.int32_t) { ... }
//
//	// _cgo_export.c, generated by cmd/cgo
//	struct proxylibbox_Thing_GetName_return { nstring r0; int32_t r1; };
//	...
//	typedef struct {
//		int32_t recv;
//		char __pad0[4];
//		nstring r0;
//		int32_t r1;
//	} __attribute__((__packed__)) _cgo_argtype;
//	_cgo_argtype _cgo_a = _cgo_zero;                 // a LOCAL, therefore byte-aligned
//	crosscall2(_cgoexp_..., &_cgo_a, 28, _cgo_ctxt);
//
// `nstring` is `struct { void *chars; ptrdiff_t len; }` and `nbyteslice` is
// `struct { void *ptr; ptrdiff_t len; }`: both carry a Go/C pointer in the frame. On
// the Go side cgo generates
//
//	func _cgoexp_..._proxylibbox_Thing_GetName(a *struct {
//		recv int32
//		r0   _Ctype_nstring
//		r1   _Ctype_int32_t
//	}) { a.r0, a.r1 = proxylibbox_Thing_GetName(a.recv); _cgoCheckResult(a.r0) }
//
// so the Go runtime stores a pointer into a C frame that cmd/cgo declares with
// __attribute__((packed)) - i.e. with alignment 1, not 8. Go <= 1.25 does that with a
// write barrier, and when the barrier degrades to runtime.typedmemmove ->
// runtime.bulkBarrierPreWrite (the shape it picks depends on the compiler's lowering of
// the aggregate store, not on anything in this repository), bulkBarrierPreWrite throws
//
//	fatal error: bulkBarrierPreWrite: unaligned arguments
//
// the moment the C frame happens to land off an 8-byte boundary. That is a runtime
// THROW, not a panic: it unwinds nothing, it cannot be recovered, and it kills the
// process. See https://github.com/golang/go/issues/46893 and the fix that finally landed
// for Go 1.26 (CL 692935, commit d5b950399), which changes exactly this typedef to
// `__attribute__((packed, aligned(N)))`. Our toolchain (go1.25.5) predates that fix.
//
// # What this check flags, and what it deliberately does not
//
// Flagged: an exported method (or package-level function) whose RESULT is `string`,
// `[]byte`, or a locally declared named type whose underlying kind is one of those. Those
// are the only result types that put a pointer into the packed result frame; every other
// shape gomobile accepts (`*X` bound object, interface/iterator, scalar, error) becomes
// int32_t, and a struct result is not bindable at all.
//
// Not flagged, on purpose:
//   - STRUCT FIELDS. An exported field produces its own `..._<Field>_Get`/`_Set`
//     `//export` function, which is a different declaration from a method and has a
//     one-pointer-word frame. This test walks method declarations and never looks at
//     struct fields, so it does not flag the accessor of StringBox - the very workaround
//     (experimental/libbox/panic.go) that this project uses for the flagged shape.
//   - Unexported methods, and methods on unexported types: gomobile never binds them.
//   - Methods whose signature gomobile rejects (unexported parameter/result types, and
//     named types whose underlying kind is neither pointer nor interface): cmd/gobind
//     prints "// skipped method ... with unsupported parameter or return types" and the
//     method simply never reaches the platform. Note that a named STRING type falls in
//     this bucket today, which is why it is flagged rather than excused: either it stays
//     unbound (a silently missing API) or a future gobind starts binding it and it
//     becomes a bare string result frame.
//
// # The baseline is a debt register, not an exemption
//
// libbox already ships the flagged shape in a number of places (see
// gomobileResultDebt). They are grandfathered so that this check can be green today and
// still catch the NEXT one; the task this test exists for is "no NEW dangerous result
// signature". The register is checked in both directions: a flagged declaration that is
// not listed fails, AND a listed declaration that no longer exists (or is no longer
// flagged) fails, so the list can only shrink and cannot rot into a mute allowlist. Each
// entry carries the concrete reason it was not converted, and the dominant reason is that
// converting it changes a signature that a shipped client calls or implements today.
//
// # Apple vs Android
//
// The check is platform-neutral: it reads Go source with go/parser, so it makes no
// assumption about GOOS, GOARCH, build tags, or the binding language. That is also the
// honest answer to "does the same risk exist on Apple": the packed `_cgo_argtype` is
// emitted by cmd/cgo's writeExports, which is shared by -lang=java and -lang=objc - the
// Objective-C binding calls the exact same `//export proxy...` symbols, and
// objc/seq_darwin.h's `nstring` has the same `{void *, NSUInteger}` layout. The original
// reports on golang/go#46893 were iOS crashes. So the hazard is a property of the toolchain
// plus the platform C compiler's frame layout on arm64, not of Android; Android/arm64 is
// simply where it has been observed most. What I could NOT verify here is whether any
// specific existing declaration actually throws on a device: that depends on the frame
// offset clang chooses and on the Go compiler's barrier lowering, neither of which is
// visible from the source. This check therefore reasons about the shape that the Go team's
// own alignment fix (and its test matrix, which includes a plain `ReturnString`) treats as
// alignment-sensitive, rather than pretending to prove a crash per method.

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

// gomobileResultClass is the classification of one result type for exactly the question
// this tripwire asks: does the C result frame carry a pointer?
type gomobileResultClass int

const (
	gomobileResultScalar gomobileResultClass = iota
	gomobileResultError
	gomobileResultBoundRef    // *T: gomobile passes an int32_t refnum, no pointer
	gomobileResultInterface   // a bound/external interface: also a refnum
	gomobileResultString      // string -> C.nstring{void*, len}
	gomobileResultBytes       // []byte -> C.nbyteslice{void*, len}
	gomobileResultNamedString // a local named type whose underlying kind is string
	gomobileResultNamedBytes  // a local named type whose underlying kind is []byte
	gomobileResultUnsupported // gobind rejects the signature and skips the method
	gomobileResultUnresolved  // named type declared outside this package
)

// pointerBearing reports whether the class puts a Go pointer in the packed result frame.
func (c gomobileResultClass) pointerBearing() bool {
	switch c {
	case gomobileResultString, gomobileResultBytes, gomobileResultNamedString, gomobileResultNamedBytes:
		return true
	}
	return false
}

func (c gomobileResultClass) String() string {
	switch c {
	case gomobileResultScalar:
		return "scalar"
	case gomobileResultError:
		return "error"
	case gomobileResultBoundRef:
		return "bound object (*T -> refnum)"
	case gomobileResultInterface:
		return "interface/iterator (refnum)"
	case gomobileResultString:
		return "bare string"
	case gomobileResultBytes:
		return "bare []byte"
	case gomobileResultNamedString:
		return "named string type"
	case gomobileResultNamedBytes:
		return "named []byte type"
	case gomobileResultUnsupported:
		return "unsupported by gobind (method is skipped)"
	case gomobileResultUnresolved:
		return "external named type (unresolvable from source; never pointer-bearing)"
	}
	return "unknown"
}

// gomobileSurfaceEntry is one exported declaration gomobile reaches: a method on a bound
// type (struct methods and interface methods alike - gomobile emits the same //export
// wrapper for both) or a package-level function. Struct fields are intentionally absent.
type gomobileSurfaceEntry struct {
	owner     string // bound type name; empty for a package-level function
	name      string
	isIface   bool
	results   []string
	classes   []gomobileResultClass
	position  string
	methodStr string // source-level signature, for messages
}

func (e gomobileSurfaceEntry) key() string {
	if e.owner == "" {
		return e.name
	}
	return e.owner + "." + e.name
}

// frameReason describes the flagged result the way the failure message needs it.
func (e gomobileSurfaceEntry) flaggedResults() []string {
	var flagged []string
	for i, class := range e.classes {
		if class.pointerBearing() {
			flagged = append(flagged, fmt.Sprintf("%s (%s)", e.results[i], class))
		}
	}
	return flagged
}

// summary renders the class column of the inventory: every result of the declaration,
// with the flagged ones called out in full.
func (e gomobileSurfaceEntry) summary() string {
	if len(e.classes) == 0 {
		return "void"
	}
	parts := make([]string, 0, len(e.classes))
	for i, class := range e.classes {
		if class.pointerBearing() {
			parts = append(parts, "BARE STRING/BYTES RESULT ("+e.results[i]+")")
			continue
		}
		parts = append(parts, class.String())
	}
	return strings.Join(parts, " + ")
}

// gomobileResultDebt is the explicit register of pre-existing flagged declarations. The
// key is "<Type>.<Method>" for methods and "<Func>" for package-level functions. Values
// are the reason the declaration was NOT converted in this change, plus the shipped call
// sites a future conversion has to move. Nothing may be added here without a reason: the
// point of the register is that it only ever shrinks.
//
// This sweep converted seven entries to the safe shape - a bound *StringBox read through its
// Value accessor - and deleted them from the register:
//
//	TunOptions.GetHTTPProxyServer   Apple-only call site; Swift moved to .value in the
//	                                clients/apple worktree cut from the recorded gitlink
//	RoutePrefix.Mask                Apple-only call site; same worktree
//	RoutePrefix.Address             Apple + Android call sites; Android moved in place
//	DeprecatedNote.Message          Apple + Android call sites; both moved
//	BridgeSession.Name              Apple + Android call sites; both moved
//	DeprecatedNote.MessageWithLink  no call site anywhere; a pure frame-shape removal
//	OnDemandRule.ProbeURL           no implementation or call site anywhere; the interface
//	                                had no producer or consumer, so the frame was latent
//
// The register's stale check is the other half of the proof: those keys are gone, and the
// tripwire fails if a converted declaration is ever changed back to a bare result.
var gomobileResultDebt = map[string]string{
	// Connection lives in command_types.go, which is owned by another change in flight and is
	// not modifiable here. The call sites are recorded so the conversion can be finished by
	// whoever owns that file.
	"Connection.DisplayDestination": debtCallSites(debtDisplayDestination,
		"clients/apple/ApplicationLibrary/Views/Connections/ConnectionListViewModel.swift:175 (goConnection.displayDestination())",
		"clients/android/app/src/main/java/io/nekohasekai/sfa/compose/model/Connection.kt:97 (connection.displayDestination())"),

	// []byte results. No safe shape exists in this package today - see debtEncodedBytesResult.
	"ErrorMessage.Encode": debtCallSites(debtEncodedBytesResult,
		"clients/apple/ApplicationLibrary/Service/ProfileServer.swift:163 (errorMessage.encode())"),
	"ProfileContent.Encode": debtCallSites(debtEncodedBytesResult,
		"clients/apple/Library/Database/Profile+Transferable.swift:57,208,229 and ApplicationLibrary/Service/ProfileServer.swift:137 (content.encode())",
		"clients/android/app/src/main/java/io/nekohasekai/sfa/ktx/Shares.kt:34, .../dashboard/ProfilesCard.kt:638, .../dashboard/ProfilePickerSheet.kt:204 (content.encode())"),
	"ProfileContentRequest.Encode": debtCallSites(debtEncodedBytesResult,
		"clients/apple/ApplicationLibrary/Views/Profile/ImportProfileViewModel.swift:121 (request.encode())"),
	"ProfileEncoder.Encode": debtCallSites(debtEncodedBytesResult,
		"clients/apple/ApplicationLibrary/Service/ProfileServer.swift:157 (encoder.encode())"),

	// The platform implements these (Kotlin PlatformInterfaceWrapper / Swift
	// ExtensionPlatformInterface) and Go only consumes them, so the shipped path is the Go -> C
	// cproxy call, whose C struct result is copied into a Go stack slot that cgo always lays out
	// aligned. cmd/gobind still emits the C -> Go //export wrapper, but no shipped client reaches
	// it, so the flagged frame is unreachable. Converting them would rewrite the protocol the
	// platform conforms to, which is a larger change than the risk it removes.
	"PlatformInterface.LookupSFTPServer":     debtPlatformImplemented,
	"PlatformInterface.ReadSystemSSHHostKey": debtPlatformImplemented,
	"PlatformInterface.TailscaleHostname":    debtPlatformImplemented,

	// String() is fmt.Stringer; the iterator is generic and is also implemented by the
	// platform when it hands a string list INTO Go.
	"RoutePrefix.String":  debtStringer,
	"StringIterator.Next": debtIterator,

	// Package-level helpers. They have no bound object to hang an accessor on, they are part of
	// the published surface of the AAR/XCFramework as static methods, and their single result is
	// one pointer word. The call sites are recorded so a future sweep knows the blast radius.
	"EncodeChunkedMessage": debtCallSites(debtUtilityFunction,
		"clients/apple/Library/Network/NWSocket.swift"),
	"FormatBitrate": debtCallSites(debtUtilityFunction,
		"clients/apple/ApplicationLibrary/Views/Tools/NetworkQualityView.swift"),
	"FormatBytes": debtCallSites(debtUtilityFunction,
		"clients/apple: MacLibrary/StatusBarController.swift, ApplicationLibrary/Views/Tools/TaildropView.swift, .../Dashboard/Cards/UploadTrafficCard.swift, .../DownloadTrafficCard.swift, .../Components/ExtensionStatusView.swift, .../Connections/ConnectionView.swift, ConnectionDetailsView.swift, ConnectionListView.swift, .../Setting/CoreView.swift"),
	"FormatDuration": debtCallSites(debtUtilityFunction,
		"clients/apple/ApplicationLibrary/Views/Connections/ConnectionView.swift"),
	"FormatFQDN": debtCallSites(debtUtilityFunction,
		"clients/apple/ApplicationLibrary/Views/Tools/TailscalePeerView.swift",
		"clients/android/app/src/main/java/io/nekohasekai/sfa/compose/screen/tools/TailscalePeerScreen.kt"),
	"FormatMemoryBytes": debtCallSites(debtUtilityFunction,
		"clients/apple/ApplicationLibrary/Views/Tools/OOMReportListView.swift, .../Dashboard/Cards/StatusCard.swift, .../Components/ExtensionStatusView.swift"),
	"FormatNATFiltering": debtCallSites(debtUtilityFunction,
		"clients/apple/ApplicationLibrary/Views/Tools/STUNTestView.swift"),
	"FormatNATMapping": debtCallSites(debtUtilityFunction,
		"clients/apple/ApplicationLibrary/Views/Tools/STUNTestView.swift"),
	"GenerateRemoteProfileImportLink": debtCallSites(debtUtilityFunction,
		"clients/apple/Library/Database/Profile+Share.swift, .../Views/Profile/QRCodeSheet.swift",
		"clients/android/app/src/main/java/io/nekohasekai/sfa/compose/screen/dashboard/ProfilesCard.kt, ProfilePickerSheet.kt"),
	"GoVersion": debtCallSites(debtUtilityFunction,
		"clients/apple/Library/Shared/CrashReportManager.swift"),
	// GoroutineDump is the one utility with no caller in Go, Apple or Android: it is dead API,
	// and only the checked-in prebuilt headers still name it. It is held here rather than
	// converted because the instruction for package-level helpers is to leave them registered,
	// and converting a published static method that nothing calls is pure API churn. Deleting
	// the function outright would remove the entry as well and is the better future cleanup.
	"GoroutineDump": debtUtilityFunction,
	"ProxyDisplayType": debtCallSites(debtUtilityFunction,
		"clients/apple/Library/Network/OutboundGroup.swift",
		"clients/android/app/src/main/java/io/nekohasekai/sfa/compose/screen/tools/OutboundPickerScreen.kt, .../compose/model/Groups.kt"),
	"Version": debtCallSites(debtUtilityFunction,
		"clients/apple/Library/Network/HTTPClient.swift, Library/Shared/CrashReportManager.swift, Library/Shared/Variant.swift, ApplicationLibrary/Views/Setting/CoreView.swift"),
}

const (
	// command_types.go is owned by another in-flight change, so this declaration's method set
	// cannot be edited by the gomobile sweep regardless of how reachable it is.
	debtDisplayDestination = "pre-existing; declared in command_types.go, which this change does not own"
	// []byte is the shape with no existing safe home. *StringBox is for text and these payloads
	// are binary (ProfileContent.Encode gzips its body), so a string round-trip would corrupt
	// them; the existing iterators are for lists, and a per-byte platform round trip would turn
	// one socket write into N calls; a result struct is the shape for several scalar fields. The
	// remaining options are to invent a BytesBox type - exactly the API invention this register
	// exists to avoid - or to wait for the Go 1.26 cmd/cgo alignment fix (CL 692935) that the
	// pinned toolchain predates.
	debtEncodedBytesResult = "pre-existing; a []byte result has no bound-object, iterator or result-struct shape " +
		"in this package that preserves an opaque binary wire frame"
	// PlatformInterface, OnDemandRule and friends are supplied BY the platform and only
	// consumed by Go, so the shipped path is the Go -> C cproxy call: its C struct result is
	// copied into a Go stack slot, which cgo always lays out aligned. cmd/gobind still emits
	// the C -> Go //export wrapper, but no shipped client reaches it.
	debtPlatformImplemented = "pre-existing; the interface is implemented by the platform, so the shipped " +
		"path is the Go->C cproxy call and the packed C->Go //export frame is not exercised by the clients"
	debtStringer = "pre-existing; this method is fmt.Stringer, so it must keep returning string " +
		"(changing it would silently change every fmt formatting of the type)"
	debtIterator = "pre-existing; Next is declared on the generic iterator[T] and the string instantiation is " +
		"required by every []string result in the surface; the platform also implements StringIterator when " +
		"passing string lists into Go"
	debtUtilityFunction = "pre-existing; package-level helper with a single pointer-bearing result and no bound " +
		"object to move the accessor to; converting it would rename a published API for no frame-shape gain"
)

// debtCallSites renders the reason together with the shipped call sites a conversion has to
// move. Recording them per entry is the point of this sweep: "a shipped client calls it" was
// true for most entries but told the next reader nothing they could act on.
func debtCallSites(reason string, callSites ...string) string {
	if len(callSites) == 0 {
		return reason
	}
	return reason + " Shipped call sites that must move with it: " + strings.Join(callSites, "; ") + "."
}

// TestGomobileMethodResultSurface is the tripwire. It walks the source of this package,
// derives the gomobile-reachable surface, and fails when a declaration carries a
// pointer-bearing result frame that the register does not account for.
func TestGomobileMethodResultSurface(t *testing.T) {
	entries := scanGomobileSurface(t, ".")

	existing := make(map[string]bool, len(entries))
	flagged := make(map[string]bool)
	for _, entry := range entries {
		existing[entry.key()] = true
		if len(entry.flaggedResults()) > 0 {
			flagged[entry.key()] = true
		}
	}

	var offenders []gomobileSurfaceEntry
	for _, entry := range entries {
		if len(entry.flaggedResults()) == 0 {
			continue
		}
		if _, registered := gomobileResultDebt[entry.key()]; registered {
			continue
		}
		offenders = append(offenders, entry)
	}

	// Fail first on anything new, with the full explanation, because that is the case a
	// developer hitting this needs to understand.
	for _, entry := range offenders {
		kind := "function"
		if entry.owner != "" {
			kind = "method"
			if entry.isIface {
				kind = "interface method"
			}
		}
		t.Errorf(`new gomobile result frame carries a Go pointer: %s %s
  declared at %s
  result: %s
  frame slot: %s

  gomobile reaches this through an //export function whose C result frame is packed
  (__attribute__((packed)) => alignment 1) and holds nstring/nbyteslice, i.e. a raw
  pointer. The Go side stores that pointer through the C frame with a write barrier, and
  when the barrier lowers to runtime.typedmemmove -> runtime.bulkBarrierPreWrite on a
  frame that is not 8-byte aligned the runtime THROWS:

      fatal error: bulkBarrierPreWrite: unaligned arguments

  That is a throw, not a panic: the process is killed and nothing can recover it. Go
  1.26 aligns this frame (cmd/cgo CL 692935); the toolchain pinned here does not.

  Return a bound object instead of the raw value, exactly as the rest of this package
  does:
    - string  -> *StringBox, built with wrapString(), read through its Value accessor
                 (experimental/libbox/panic.go; precedent: TunOptions.GetDNSMode)
    - []byte or a list -> an existing ...Iterator type (precedent: TunOptions.GetDNSServerAddress)
    - several fields -> a *SomeResult struct with accessors
  If the signature genuinely cannot change because a shipped client calls it, add the key
  %q to gomobileResultDebt WITH the reason, and make it a planned migration.`,
			kind, entry.methodStr, entry.position, strings.Join(entry.results, ", "),
			strings.Join(entry.flaggedResults(), ", "), entry.key())
	}

	// The register is a debt register: it must not outlive the code it describes, and it
	// must not claim a declaration that is no longer flagged.
	var stale []string
	for key, reason := range gomobileResultDebt {
		switch {
		case !existing[key]:
			stale = append(stale, fmt.Sprintf("%s: no such bound declaration any more (%s)", key, reason))
		case !flagged[key]:
			stale = append(stale, fmt.Sprintf("%s: exists but no longer has a pointer-bearing result (%s)", key, reason))
		}
	}
	sort.Strings(stale)
	for _, entry := range stale {
		t.Errorf("gomobileResultDebt is stale: %s\ndelete the entry - the register may only shrink", entry)
	}

	var boundCount = len(entries)
	t.Logf("gomobile surface: %d bound declarations, %d with a pointer-bearing result (%d registered as debt)",
		boundCount, len(flagged), len(gomobileResultDebt))

	// The complete inventory. It is logged rather than asserted: `go test -v -run
	// TestGomobileMethodResultSurface ./experimental/libbox` is what a reviewer or a
	// downstream platform author runs to see the whole bound surface and its classes
	// without reading the source.
	if testing.Verbose() {
		var inventory strings.Builder
		inventory.WriteString("\ntype | method | result type | class\n")
		for _, entry := range entries {
			typeColumn := entry.owner
			if typeColumn == "" {
				typeColumn = "(package function)"
			}
			resultColumn := "(none)"
			if len(entry.results) > 0 {
				resultColumn = strings.Join(entry.results, ", ")
			}
			fmt.Fprintf(&inventory, "%s | %s | %s | %s\n", typeColumn, entry.name, resultColumn, entry.summary())
		}
		t.Log(inventory.String())
	}
}

// scanGomobileSurface parses this package's source (all non-test .go files, including
// files excluded by the current build tags, so that an Android-only declaration is still
// seen from a macOS checkout) and mirrors cmd/gobind's own reachability rules:
//
//   - every exported local type whose underlying type is a struct or an interface is
//     bound; interfaces contribute their method set, structs contribute their exported
//     methods (methods declared with a value or a pointer receiver);
//   - every exported package-level function is bound;
//   - nothing else is.
//
// It is a source-level check on purpose: it must stay platform-neutral and must not add
// a dependency (golang.org/x/tools/go/packages would turn an indirect requirement into a
// direct one). The cost is that named types declared outside this package cannot be
// resolved; that is fine, because gomobile rejects such a result unless its underlying
// kind is a pointer or an interface, and both are refnums either way.
func scanGomobileSurface(t *testing.T, dir string) []gomobileSurfaceEntry {
	t.Helper()

	fileSet := token.NewFileSet()
	var parsed []*ast.File
	dirEntries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("read package directory: %v", err)
	}
	for _, dirEntry := range dirEntries {
		name := dirEntry.Name()
		if dirEntry.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		file, err := parser.ParseFile(fileSet, filepath.Join(dir, name), nil, parser.SkipObjectResolution)
		if err != nil {
			t.Fatalf("parse %s: %v", name, err)
		}
		parsed = append(parsed, file)
	}
	if len(parsed) == 0 {
		t.Fatal("no package sources found to scan")
	}

	// Local type declarations, so that `type X string` and `type X Y` chains resolve and
	// so that `type A B` where B is a struct is still recognised as a bound struct.
	localTypes := make(map[string][]ast.Expr)
	for _, file := range parsed {
		for _, decl := range file.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.TYPE {
				continue
			}
			for _, spec := range genDecl.Specs {
				typeSpec := spec.(*ast.TypeSpec)
				localTypes[typeSpec.Name.Name] = append(localTypes[typeSpec.Name.Name], typeSpec.Type)
			}
		}
	}

	// resolveShape walks local named types down to the shape cmd/gobind would see. It
	// returns one of: interface, struct, string, bytes, scalar, error, pointer, external,
	// or unsupported. `unsupported` means gobind's isSupported() rejects the type, so the
	// whole declaration is skipped rather than bound.
	var resolveShape func(expr ast.Expr, depth int) string
	resolveShape = func(expr ast.Expr, depth int) string {
		if depth > 16 {
			return "unsupported"
		}
		switch typed := expr.(type) {
		case *ast.Ident:
			switch typed.Name {
			case "string":
				return "string"
			case "error":
				return "error"
			case "bool", "int", "int8", "int16", "int32", "int64",
				"uint", "uint8", "uint16", "uint32", "uint64", "uintptr",
				"float32", "float64", "rune", "byte":
				return "scalar"
			}
			variants, local := localTypes[typed.Name]
			if !local {
				return "external"
			}
			// Prefer the most dangerous variant: build-tag variants of the same name must
			// never be allowed to hide a pointer-bearing kind behind a safe sibling.
			resolved := "unsupported"
			for _, variant := range variants {
				shape := resolveShape(variant, depth+1)
				switch {
				case shape == "string" || shape == "bytes":
					return shape
				case shape == "interface" || shape == "struct" || shape == "pointer" || shape == "scalar":
					resolved = shape
				}
			}
			return resolved
		case *ast.StarExpr:
			return "pointer"
		case *ast.SelectorExpr:
			// Declared in another package: gomobile needs a pointer or interface
			// underlying type to accept it, and a pointer/interface is a refnum.
			return "external"
		case *ast.ArrayType:
			// Only the predeclared []byte/[]uint8 binds (as C.nbyteslice); cmd/gobind
			// matches on the element's *types.Basic kind, so []MyByte is rejected too.
			if typed.Len != nil {
				return "unsupported"
			}
			if isByteIdent(typed.Elt) {
				return "bytes"
			}
			return "unsupported"
		case *ast.InterfaceType:
			return "interface"
		case *ast.StructType:
			return "struct"
		case *ast.MapType, *ast.ChanType, *ast.FuncType, *ast.Ellipsis:
			return "unsupported"
		}
		return "unsupported"
	}

	// boundShape decides whether an exported type is bound at all.
	boundShapes := make(map[string]string)
	for name := range localTypes {
		if !ast.IsExported(name) {
			continue
		}
		shape := resolveShape(ast.NewIdent(name), 0)
		if shape == "struct" || shape == "interface" {
			boundShapes[name] = shape
		}
	}

	classify := func(expr ast.Expr) (gomobileResultClass, string) {
		switch resolveShape(expr, 0) {
		case "string":
			// The bare predeclared string, versus `type Foo string` used as a result.
			if ident, direct := expr.(*ast.Ident); direct && ident.Name == "string" {
				return gomobileResultString, "string"
			}
			return gomobileResultNamedString, "named string"
		case "bytes":
			if _, direct := expr.(*ast.ArrayType); direct {
				return gomobileResultBytes, "[]byte"
			}
			return gomobileResultNamedBytes, "named []byte"
		case "error":
			return gomobileResultError, "error"
		case "scalar":
			return gomobileResultScalar, "scalar"
		case "pointer":
			return gomobileResultBoundRef, "bound object"
		case "interface":
			return gomobileResultInterface, "interface"
		case "struct":
			// A struct result is not bindable: cmd/gobind skips the declaration.
			return gomobileResultUnsupported, "struct value"
		case "external":
			return gomobileResultUnresolved, "external named type"
		}
		return gomobileResultUnsupported, "unsupported"
	}

	var entries []gomobileSurfaceEntry
	record := func(owner, name string, isIface bool, funcType *ast.FuncType, position token.Position) {
		entry := gomobileSurfaceEntry{
			owner:    owner,
			name:     name,
			isIface:  isIface,
			position: position.String(),
		}
		if owner == "" {
			entry.methodStr = name
		} else {
			entry.methodStr = owner + "." + name
		}
		if funcType.Results == nil {
			entries = append(entries, entry)
			return
		}
		for _, result := range funcType.Results.List {
			repeats := len(result.Names)
			if repeats == 0 {
				repeats = 1
			}
			class, rendered := classify(result.Type)
			for i := 0; i < repeats; i++ {
				entry.results = append(entry.results, rendered)
				entry.classes = append(entry.classes, class)
			}
		}
		entries = append(entries, entry)
	}

	// Interface method sets, including embedded interfaces, because gomobile generates an
	// //export wrapper for every method in the set.
	var interfaceMethods func(name string, seen map[string]bool) []*ast.Field
	interfaceDecls := make(map[string]*ast.InterfaceType)
	for _, file := range parsed {
		for _, decl := range file.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.TYPE {
				continue
			}
			for _, spec := range genDecl.Specs {
				typeSpec := spec.(*ast.TypeSpec)
				if interfaceType, ok := typeSpec.Type.(*ast.InterfaceType); ok {
					interfaceDecls[typeSpec.Name.Name] = interfaceType
				}
			}
		}
	}
	interfaceMethods = func(name string, seen map[string]bool) []*ast.Field {
		if seen[name] {
			return nil
		}
		seen[name] = true
		interfaceType, ok := interfaceDecls[name]
		if !ok || interfaceType.Methods == nil {
			return nil
		}
		var fields []*ast.Field
		for _, field := range interfaceType.Methods.List {
			if _, isFunc := field.Type.(*ast.FuncType); isFunc {
				fields = append(fields, field)
				continue
			}
			embedded := typeName(field.Type)
			if embedded == "" {
				continue
			}
			fields = append(fields, interfaceMethods(embedded, seen)...)
		}
		return fields
	}

	for _, file := range parsed {
		for _, decl := range file.Decls {
			switch typed := decl.(type) {
			case *ast.FuncDecl:
				if !ast.IsExported(typed.Name.Name) {
					continue
				}
				if typed.Recv == nil || len(typed.Recv.List) == 0 {
					record("", typed.Name.Name, false, typed.Type, fileSet.Position(typed.Pos()))
					continue
				}
				owner := typeName(typed.Recv.List[0].Type)
				if _, bound := boundShapes[owner]; !bound {
					continue
				}
				record(owner, typed.Name.Name, boundShapes[owner] == "interface", typed.Type, fileSet.Position(typed.Pos()))
			case *ast.GenDecl:
				if typed.Tok != token.TYPE {
					continue
				}
				for _, spec := range typed.Specs {
					typeSpec := spec.(*ast.TypeSpec)
					if !ast.IsExported(typeSpec.Name.Name) {
						continue
					}
					if _, bound := boundShapes[typeSpec.Name.Name]; !bound {
						continue
					}
					if _, isInterface := typeSpec.Type.(*ast.InterfaceType); !isInterface {
						continue
					}
					for _, field := range interfaceMethods(typeSpec.Name.Name, make(map[string]bool)) {
						funcType, ok := field.Type.(*ast.FuncType)
						if !ok {
							continue
						}
						for _, methodName := range field.Names {
							if !ast.IsExported(methodName.Name) {
								continue
							}
							record(typeSpec.Name.Name, methodName.Name, true, funcType, fileSet.Position(methodName.Pos()))
						}
					}
				}
			}
		}
	}

	sort.Slice(entries, func(i, j int) bool {
		if entries[i].key() != entries[j].key() {
			return entries[i].key() < entries[j].key()
		}
		return entries[i].position < entries[j].position
	})
	return entries
}

// typeName renders the named type behind a receiver or an embedded interface entry,
// unwrapping pointers and generic instantiation.
func typeName(expr ast.Expr) string {
	switch typed := expr.(type) {
	case *ast.Ident:
		return typed.Name
	case *ast.StarExpr:
		return typeName(typed.X)
	case *ast.IndexExpr:
		return typeName(typed.X)
	case *ast.IndexListExpr:
		return typeName(typed.X)
	}
	return ""
}

// isByteIdent reports whether the element type of a slice is byte/uint8, which is the
// only slice kind gomobile binds (as C.nbyteslice).
func isByteIdent(expr ast.Expr) bool {
	ident, ok := expr.(*ast.Ident)
	if !ok {
		return false
	}
	return ident.Name == "byte" || ident.Name == "uint8"
}
